"""initial schema

Revision ID: 1f0c0bc38ff4
Revises:
Create Date: 2026-09-09 01:25:30.376412
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1f0c0bc38ff4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cameras",
        sa.Column("camera_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("clock_offset_s", sa.Float(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("fps", sa.Float(), nullable=False),
        sa.Column("calibration_ref", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("camera_id"),
    )
    op.create_table(
        "processing_runs",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=128), nullable=False),
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("model_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("device", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        op.f("ix_processing_runs_input_hash"), "processing_runs", ["input_hash"], unique=False
    )
    op.create_index(op.f("ix_processing_runs_status"), "processing_runs", ["status"], unique=False)
    op.create_table(
        "events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("timestamp_s", sa.Float(), nullable=False),
        sa.Column("camera_id", sa.String(length=64), nullable=True),
        sa.Column("entity_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("zone_id", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["processing_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index("ix_event_run_time", "events", ["run_id", "timestamp_s"], unique=False)
    op.create_index(op.f("ix_events_event_type"), "events", ["event_type"], unique=False)
    op.create_index(op.f("ix_events_run_id"), "events", ["run_id"], unique=False)
    op.create_index(op.f("ix_events_timestamp_s"), "events", ["timestamp_s"], unique=False)
    op.create_table(
        "observations",
        sa.Column("observation_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("camera_id", sa.String(length=64), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("timestamp_s", sa.Float(), nullable=False),
        sa.Column("entity_class", sa.String(length=32), nullable=False),
        sa.Column("x1", sa.Float(), nullable=False),
        sa.Column("y1", sa.Float(), nullable=False),
        sa.Column("x2", sa.Float(), nullable=False),
        sa.Column("y2", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("world_xyz", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("visibility", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.camera_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["processing_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    op.create_index(
        "ix_obs_run_camera_time",
        "observations",
        ["run_id", "camera_id", "timestamp_s"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observations_entity_class"), "observations", ["entity_class"], unique=False
    )
    op.create_index(op.f("ix_observations_run_id"), "observations", ["run_id"], unique=False)
    op.create_index(op.f("ix_observations_track_id"), "observations", ["track_id"], unique=False)
    op.create_table(
        "track_segments",
        sa.Column("segment_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("camera_id", sa.String(length=64), nullable=False),
        sa.Column("local_track_id", sa.String(length=64), nullable=False),
        sa.Column("entity_class", sa.String(length=32), nullable=False),
        sa.Column("start_time_s", sa.Float(), nullable=False),
        sa.Column("end_time_s", sa.Float(), nullable=False),
        sa.Column("observation_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mean_confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.camera_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["processing_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("segment_id"),
    )
    op.create_index(op.f("ix_track_segments_run_id"), "track_segments", ["run_id"], unique=False)
    op.create_table(
        "identity_links",
        sa.Column("link_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("segment_a", sa.String(length=64), nullable=False),
        sa.Column("segment_b", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["processing_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["segment_a"],
            ["track_segments.segment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["segment_b"],
            ["track_segments.segment_id"],
        ),
        sa.PrimaryKeyConstraint("link_id"),
    )
    op.create_index(
        op.f("ix_identity_links_decision"), "identity_links", ["decision"], unique=False
    )
    op.create_index(op.f("ix_identity_links_run_id"), "identity_links", ["run_id"], unique=False)
    op.create_table(
        "incidents",
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("incident_class", sa.String(length=64), nullable=False),
        sa.Column("trigger_event_id", sa.String(length=64), nullable=False),
        sa.Column("detected_at_s", sa.Float(), nullable=False),
        sa.Column("window_start_s", sa.Float(), nullable=False),
        sa.Column("window_end_s", sa.Float(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["processing_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["trigger_event_id"],
            ["events.event_id"],
        ),
        sa.PrimaryKeyConstraint("incident_id"),
    )
    op.create_index(
        op.f("ix_incidents_incident_class"), "incidents", ["incident_class"], unique=False
    )
    op.create_index(op.f("ix_incidents_run_id"), "incidents", ["run_id"], unique=False)
    op.create_index(op.f("ix_incidents_severity"), "incidents", ["severity"], unique=False)
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_table(
        "evidence_nodes",
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("node_type", sa.String(length=32), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("timestamp_s", sa.Float(), nullable=True),
        sa.Column("interval_start_s", sa.Float(), nullable=True),
        sa.Column("interval_end_s", sa.Float(), nullable=True),
        sa.Column("source_ref", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.incident_id"],
        ),
        sa.PrimaryKeyConstraint("node_id"),
    )
    op.create_index(
        op.f("ix_evidence_nodes_incident_id"), "evidence_nodes", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_nodes_node_type"), "evidence_nodes", ["node_type"], unique=False
    )
    op.create_index(op.f("ix_evidence_nodes_run_id"), "evidence_nodes", ["run_id"], unique=False)
    op.create_table(
        "hypotheses",
        sa.Column("hypothesis_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence_level", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("support_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contradiction_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.incident_id"],
        ),
        sa.PrimaryKeyConstraint("hypothesis_id"),
    )
    op.create_index(op.f("ix_hypotheses_incident_id"), "hypotheses", ["incident_id"], unique=False)
    op.create_index(op.f("ix_hypotheses_run_id"), "hypotheses", ["run_id"], unique=False)
    op.create_index(op.f("ix_hypotheses_score"), "hypotheses", ["score"], unique=False)
    op.create_table(
        "reports",
        sa.Column("report_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("generator_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("claims", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ranked_hypotheses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gaps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", sa.Text(), nullable=False),
        sa.Column("immutable", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.incident_id"],
        ),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.create_index(op.f("ix_reports_incident_id"), "reports", ["incident_id"], unique=False)
    op.create_index(op.f("ix_reports_run_id"), "reports", ["run_id"], unique=False)
    op.create_table(
        "evidence_edges",
        sa.Column("edge_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("from_node", sa.String(length=64), nullable=False),
        sa.Column("to_node", sa.String(length=64), nullable=False),
        sa.Column("relation", sa.String(length=32), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_node"],
            ["evidence_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.incident_id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_node"],
            ["evidence_nodes.node_id"],
        ),
        sa.PrimaryKeyConstraint("edge_id"),
    )
    op.create_index(
        op.f("ix_evidence_edges_incident_id"), "evidence_edges", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_edges_relation"), "evidence_edges", ["relation"], unique=False
    )
    op.create_index(op.f("ix_evidence_edges_run_id"), "evidence_edges", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_edges_run_id"), table_name="evidence_edges")
    op.drop_index(op.f("ix_evidence_edges_relation"), table_name="evidence_edges")
    op.drop_index(op.f("ix_evidence_edges_incident_id"), table_name="evidence_edges")
    op.drop_table("evidence_edges")
    op.drop_index(op.f("ix_reports_run_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_incident_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_hypotheses_score"), table_name="hypotheses")
    op.drop_index(op.f("ix_hypotheses_run_id"), table_name="hypotheses")
    op.drop_index(op.f("ix_hypotheses_incident_id"), table_name="hypotheses")
    op.drop_table("hypotheses")
    op.drop_index(op.f("ix_evidence_nodes_run_id"), table_name="evidence_nodes")
    op.drop_index(op.f("ix_evidence_nodes_node_type"), table_name="evidence_nodes")
    op.drop_index(op.f("ix_evidence_nodes_incident_id"), table_name="evidence_nodes")
    op.drop_table("evidence_nodes")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_severity"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_run_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_incident_class"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_identity_links_run_id"), table_name="identity_links")
    op.drop_index(op.f("ix_identity_links_decision"), table_name="identity_links")
    op.drop_table("identity_links")
    op.drop_index(op.f("ix_track_segments_run_id"), table_name="track_segments")
    op.drop_table("track_segments")
    op.drop_index(op.f("ix_observations_track_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_run_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_entity_class"), table_name="observations")
    op.drop_index("ix_obs_run_camera_time", table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_events_timestamp_s"), table_name="events")
    op.drop_index(op.f("ix_events_run_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index("ix_event_run_time", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_processing_runs_status"), table_name="processing_runs")
    op.drop_index(op.f("ix_processing_runs_input_hash"), table_name="processing_runs")
    op.drop_table("processing_runs")
    op.drop_table("cameras")
    # ### end Alembic commands ###
