"""add evidence access log.

Revision ID: 226601bb67e3
Revises: 1f0c0bc38ff4
Create Date: 2026-09-09 12:39:35.451023
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "226601bb67e3"
down_revision: str | None = "1f0c0bc38ff4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_access_log",
        sa.Column("access_id", sa.String(length=64), nullable=False),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=True),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_ref", sa.String(length=256), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("request_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("access_id"),
    )
    op.create_index(
        op.f("ix_evidence_access_log_accessed_at"),
        "evidence_access_log",
        ["accessed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_access_log_actor"), "evidence_access_log", ["actor"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_access_log_incident_id"),
        "evidence_access_log",
        ["incident_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_access_log_incident_id"), table_name="evidence_access_log")
    op.drop_index(op.f("ix_evidence_access_log_actor"), table_name="evidence_access_log")
    op.drop_index(op.f("ix_evidence_access_log_accessed_at"), table_name="evidence_access_log")
    op.drop_table("evidence_access_log")
    # ### end Alembic commands ###
